"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Abacus Wallet Bridge.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'resources/icon.icns', 'includes': ['sip']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app',  'PyQt6'],
)
